name: CI/CD

on:
  push:
    branches: [main]

env:
  AZURE_CONTAINERAPP_NAME: weather-api
  AZURE_RESOURCE_GROUP: weather-rg
  AZURE_CONTAINER_ENV: weather-env
  IMAGE_NAME: weather-api
  DOCKER_REGISTRY: docker.io

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend deps
        run: pip install -r backend/requirements.txt

      - name: Run backend tests with PYTHONPATH
        run: PYTHONPATH=backend pytest backend/tests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name $AZURE_CONTAINERAPP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            --environment $AZURE_CONTAINER_ENV
